# -*- coding: utf-8 -*-
"""Untitled115.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UEIllpoB5nYxbSFYXv5IWVyNGk1gOhUS
"""

import torch
import numpy as np
import matplotlib.pyplot as plt
from time import time


D = 1e-5          # դիֆուզիայի գործակից
L = 0.1           # հյուսվածքի երկարություն 0.1մ
N = 5             # տարածական բաժանումների քանակ
M = 5             # ժամանակային բաժանումների քանակ
dx = L / N        # մետր
dt = 20.0         # վայրկյան
lam = D * dt / dx**2
xs = np.linspace(0, L, N+1)
ts = np.linspace(0, M*dt, M+1)
print(f"dx={dx:.5f} մ, dt={dt:.2f} վ, λ={lam:.5f}")


dtype = torch.float64
device = torch.device("cpu")
torch.manual_seed(0)
P = torch.nn.Parameter(0.001 * torch.randn(M, N-1, dtype=dtype, device=device))
optimizer = torch.optim.SGD([P], lr=1e-2)
qayleri_qanak = 4500
tpelu_hachaxakanutyun = 500


Q = np.zeros((M, N+1))
for n in range(M):
    t_n = ts[n]
    for i in range(N+1):
        x_i = xs[i]
        Q[n, i] = x_i * (L - x_i) * 1 / (1 + t_n)**2
Q_torch = torch.tensor(Q, dtype=dtype, device=device)


t0 = time()
for qayl in range(qayleri_qanak):
    optimizer.zero_grad()
    loss = torch.tensor(0.0, dtype=dtype, device=device)
    for n in range(0, M):
        if n == 0:
            u_n = torch.zeros(N+1, dtype=dtype, device=device)   # u(x,0)=0, առաջին սկզբնական պայմանն է
        else:
            u_n = torch.cat([torch.zeros(1, dtype=dtype, device=device), P[n-1], torch.zeros(1, dtype=dtype, device=device)])
            # միավորում ենք եզրային հանգույցները (ձախ, աջ) ներքին հանգույցների հետ
        u_n1 = torch.cat([torch.zeros(1, dtype=dtype, device=device), P[n], torch.zeros(1, dtype=dtype, device=device)])
        # անցնում ենք հաջորդ ժամանակային շերտին, + միավորում ենք եզրային հանգույցները (ձախ, աջ) ներքին հանգույցների հետ
        lap = u_n[2:] - 2*u_n[1:-1] + u_n[:-2]
        mnacord = u_n1[1:-1] - u_n[1:-1] - lam * lap - dt * Q_torch[n, 1:-1]
        loss += (mnacord ** 2).sum()
    loss.backward()
    optimizer.step()
    if (qayl % tpelu_hachaxakanutyun) == 0 or qayl == qayleri_qanak - 1:
        print(f"Քայլ {qayl:4d} | կորուստ = {loss.item():.6e}")
t_verj_jamanak = time() - t0
print(f"\nՎերջ. ժամանակ = {t_verj_jamanak:.2f} վ | Վերջնական կորուստ = {loss.item():.6e}")


U_in = np.zeros((M+1, N+1), dtype=float)
for n in range(1, M+1):
    U_in[n, 1:-1] = P.detach().cpu().numpy()[n-1, :]
plt.figure(figsize=(9, 6))
for n in range(1, M+1):
    plt.plot(xs, U_in[n, :], '--', label=f"t={n*dt:.0f} վ")
plt.xlabel("Տարածական կետեր (i)")
plt.ylabel("Ջերմաստիճան, Uᵢⁿ")
plt.legend()
plt.grid(True)
plt.show()
print("\nU_in (ժամանակային շերտեր):")
print(np.round(U_in, 6))